image: docker.io/library/node

# cache:
#   paths:
#     - node_modules/

variables:
  GIT_STRATEGY: clone

pages:
  stage: deploy
  tags:
    - docker
  script:
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --prod --output-path public
      # Simulates fallthrough. See:
      # https://angular.io/guide/deployment#routed-apps-must-fallback-to-indexhtml
      # https://angular.io/guide/deployment#deploy-to-github-pages
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
    expire_in: 1 days
  only:
    - master
  except:
    - schedules

update:
  tags:
    - docker
  script:
    - git checkout -b update
    - git config user.email $GITLAB_USER_EMAIL
    - git config user.name $GITLAB_USER_NAME
    # - npm update
    - echo "change" >> ./README.md
    - |
        if [[ -n '$(git status -s)' ]]; then
          echo $GIT_TOKEN
          git commit -a -m 'updated dependencies'
          cat $GIT_TOKEN | git push -u origin 21-update-job-enhancement
        fi
  only:
    - schedules
