image: docker.io/library/node

cache:
  paths:
    - node_modules/

pages:
  stage: build
  tags:
    - docker
  script:
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --prod --output-path public
      # Simulates fallthrough. See:
      # https://angular.io/guide/deployment#routed-apps-must-fallback-to-indexhtml
      # https://angular.io/guide/deployment#deploy-to-github-pages
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
    expire_in: 1 days
  only:
    - master
  except:
    - schedules


update:
  script:
    - ./node_modules/@angular/cli/bin/ng update --all
  only:
    - schedules
