pages:
  stage: build
  image: docker.io/teracy/angular-cli
  tags:
    - docker
  script:
    - yarn install
    - ng build --prod --output-path public
    - cp public/index.html public/404.html
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - public
  # only:
    # - master
