pages:
  stage: build
  image: docker.io/library/node
  tags:
    - docker
  script:
    - npm install
    - ng build --prod --output-path public
      # Simulates fallthrough. See:
      # https://angular.io/guide/deployment#routed-apps-must-fallback-to-indexhtml
      # https://angular.io/guide/deployment#deploy-to-github-pages
    - cp public/index.html public/404.html
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - public
  # only:
  #   - master
