image: docker.io/library/node

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  tags:
    - docker
  script:
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --prod --output-path public
      # Simulates fallthrough. See:
      # https://angular.io/guide/deployment#routed-apps-must-fallback-to-indexhtml
      # https://angular.io/guide/deployment#deploy-to-github-pages
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
    expire_in: 1 days
  only:
    - master
  except:
    - schedules

update:
  tags:
    - docker
  script:
    - git checkout -b update
    - npm update
    - git config user.email $GITLAB_USER_EMAIL
    - git config user.name $GITLAB_USER_NAME
    - git commit -a -m 'updated dependencies'
    - git push -u origin update
  # only:
  #   - schedules
